import {test} from 'node:test';
import assert from 'node:assert/strict';
import {RoomService} from '../server/rooms.mjs';
function fixture(){let now=100000;const service=new RoomService({now:()=>now,countdownMs:4000,raceMs:120000});const socket=()=>({readyState:1,messages:[],send(raw){this.messages.push(JSON.parse(raw));},close(){this.readyState=3;}});const a=socket(),b=socket();const room=service.create(a,{name:'Host',color:'#aa88ff'});const add=()=>service.join(b,{code:room.code,name:'Friend',color:'#77ccff'});const ready=()=>{service.ready(a,{value:true});service.ready(b,{value:true});};const start=()=>{add();ready();service.start(a);};return{service,a,b,room,socket,add,ready,start,setNow:n=>now=n,advance:n=>now+=n};}
const latest=s=>s.messages.filter(m=>m.type==='state').at(-1);
test('private room snapshots never expose resume tokens or other players typed text',()=>{const f=fixture();f.add();const state=latest(f.b);assert.equal(state.players.length,2);assert.equal(state.code,f.room.code);assert.ok(!('token' in state.players[0]));assert.ok(!('text' in state.players[0]));assert.notEqual(f.a.messages.find(m=>m.type==='joined').token,f.b.messages.find(m=>m.type==='joined').token);});
test('only host can start; at least two connected ready players are required',()=>{const f=fixture();assert.throws(()=>f.service.start(f.a),/two drivers/);f.add();assert.throws(()=>f.service.start(f.b),/Only the host/);f.service.ready(f.a,{value:true});assert.throws(()=>f.service.start(f.a),/everyone/);f.service.ready(f.b,{value:true});f.service.start(f.a);assert.equal(f.room.status,'countdown');assert.equal(latest(f.a).startsAt,latest(f.b).startsAt);assert.equal(latest(f.a).passage,latest(f.b).passage);});
test('typing before the shared start is ignored',()=>{const f=fixture();f.start();f.service.input(f.a,{text:f.room.passage,seq:1,raceId:1});assert.equal(f.room.players[0].progress,0);assert.equal(f.room.players[0].finishedAt,null);});
test('mistakes stop progress and corrections retain accuracy history',()=>{const f=fixture();f.start();f.advance(5000);const first=f.room.passage[0];f.service.input(f.a,{text:first+'~',seq:1,raceId:1});assert.equal(f.room.players[0].progress,1/f.room.passage.length);assert.equal(latest(f.a).players[0].accuracy,50);f.service.input(f.a,{text:first,seq:2,raceId:1});f.service.input(f.a,{text:f.room.passage.slice(0,2),seq:3,raceId:1});assert.equal(latest(f.a).players[0].accuracy,67);});
test('finish ordering and WPM use server times and are immutable after finish',()=>{const f=fixture();f.start();f.advance(14000);f.service.input(f.b,{text:f.room.passage,seq:1,raceId:1});f.advance(5000);f.service.input(f.a,{text:f.room.passage,seq:1,raceId:1});assert.equal(f.room.status,'finished');const p=latest(f.a).players;assert.equal(p[1].rank,1);assert.equal(p[0].rank,2);assert.equal(p[1].wpm,Math.round(f.room.passage.length/5/(10/60)));const finish=f.room.players[1].finishedAt;f.service.input(f.b,{text:'',seq:2,raceId:1});assert.equal(f.room.players[1].finishedAt,finish);});
test('three player capacity and joining an active race are enforced',()=>{const f=fixture();f.add();f.service.join(f.socket(),{code:f.room.code,name:'Third'});assert.throws(()=>f.service.join(f.socket(),{code:f.room.code,name:'Fourth'}),/full/);const g=fixture();g.start();assert.throws(()=>g.service.join(g.socket(),{code:g.room.code,name:'Late'}),/already started/);});
test('refresh resumes the authenticated driver; invalid token cannot take a seat',()=>{const f=fixture();f.start();f.advance(5000);f.service.input(f.a,{text:f.room.passage.slice(0,8),seq:4,raceId:1});const resumeToken=f.room.players[0].token;f.service.disconnect(f.a);assert.equal(f.room.hostId,f.room.players[1].id);assert.throws(()=>f.service.resume(f.socket(),{code:f.room.code,token:'invalid'}),/expired/);const newSocket=f.socket();f.service.resume(newSocket,{code:f.room.code,token:resumeToken});assert.equal(f.room.players.length,2);assert.equal(latest(newSocket).yourText,f.room.passage.slice(0,8));assert.equal(latest(newSocket).ackSeq,4);assert.equal(f.room.players[0].connected,true);});
test('stale sequence numbers and previous-race updates do not overwrite progress',()=>{const f=fixture();f.start();f.advance(5000);f.service.input(f.a,{text:f.room.passage.slice(0,10),seq:5,raceId:1});f.service.input(f.a,{text:'',seq:4,raceId:1});f.service.input(f.a,{text:'',seq:6,raceId:0});assert.equal(f.room.players[0].text.length,10);});
test('race deadline produces DNF and host can open a fresh ready lobby',()=>{const f=fixture();f.start();f.advance(124001);f.service.tick();assert.equal(f.room.status,'finished');assert.ok(f.room.players.every(p=>p.dnf));assert.throws(()=>f.service.rematch(f.b),/Only the host/);f.service.rematch(f.a);assert.equal(f.room.status,'lobby');assert.ok(f.room.players.every(p=>!p.ready&&!p.dnf));f.ready();f.service.start(f.a);assert.equal(f.room.raceId,2);});
test('leaving mid-race forfeits the player and transfers host without stranding the race',()=>{const f=fixture();f.start();f.advance(5000);f.service.leave(f.a);assert.equal(f.room.players[0].dnf,true);assert.equal(f.room.hostId,f.room.players[1].id);f.service.input(f.b,{text:f.room.passage,seq:1,raceId:1});assert.equal(f.room.status,'finished');f.service.rematch(f.b);assert.equal(f.room.players.length,1);});
test('idle and abandoned rooms expire',()=>{const f=fixture();f.service.disconnect(f.a);f.advance(60001);f.service.tick();assert.equal(f.service.rooms.size,0);const g=fixture();g.advance(1800001);g.service.tick();assert.equal(g.service.rooms.size,0);assert.equal(g.service.members.size,0);});
test('invalid rooms, empty names, malformed text, and impersonated IDs are rejected or ignored',()=>{const f=fixture();assert.throws(()=>f.service.join(f.b,{code:'NOTAROOM',name:'Guest'}),/not found/);assert.throws(()=>f.service.join(f.b,{code:f.room.code,name:' '}),/driver name/);f.start();f.advance(5000);assert.throws(()=>f.service.input(f.a,{text:42,seq:1,raceId:1}),/Invalid typing/);f.service.handle(f.b,{type:'input',playerId:f.room.players[0].id,text:f.room.passage.slice(0,5),seq:1,raceId:1});assert.equal(f.room.players[0].progress,0);assert.ok(f.room.players[1].progress>0);});
