import React, { useState, useRef, useEffect, useCallback } from 'react';
import { createRoot } from 'react-dom/client';
import { Flag, ArrowUpRight, ArrowRight, RotateCcw, Volume2, VolumeX, Maximize2, X, Keyboard, Trophy, ChartNoAxesColumnIncreasing, ChevronDown, Check, Zap, Timer, Leaf, Settings2, Gauge, Flame, CarFront, Target, Command } from 'lucide-react';
import RaceScene from './RaceScene';
import './style.css';
import './arena.css';
import Multiplayer from './Multiplayer';
import Garage from './Garage';
import TypingSurface from './TypingSurface';

const passages = [
  'There is a certain freedom in the open road. The world moves past in a blur, and for a moment, all that matters is the journey. Find your rhythm, trust your instincts, and keep moving forward.',
  'The city was quiet in the early morning light. A warm breeze drifted through the open window, carrying the promise of a new day. Sometimes the best way to find your path is simply to begin.',
  'Great things are built one small step at a time. Slow down enough to notice the details, then let practice turn effort into instinct. Speed will follow when you find a rhythm that feels like your own.',
  'Beyond the last bend, the mountains opened into a wide valley. The road stretched toward the horizon like a ribbon of silver. We had nowhere to be and every reason to enjoy the ride.'
];
const easyPassages = ['the road is open and the sky is clear. take your time and find your flow. each small step brings you closer to where you want to go. keep your eyes ahead and enjoy the ride.', 'a new day is a chance to try again. let the past rest and look ahead. all you need is a little focus and a steady pace. you are getting better with every word you type.'];
function read(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
function App() {
 const [mode,setMode]=useState('race'), [status,setStatus]=useState('idle'), [typed,setTyped]=useState(''), [elapsed,setElapsed]=useState(0), [count,setCount]=useState(3), [index,setIndex]=useState(0), [difficulty,setDifficulty]=useState('normal'), [sound,setSound]=useState(false), [focus,setFocus]=useState(false), [modal,setModal]=useState(null), [tab,setTab]=useState(()=>new URLSearchParams(location.search).has('room')?'friends':'race'), [history,setHistory]=useState(()=>read('shift-history',[])), [color,setColor]=useState(()=>read('shift-color','#d5ef66')), [attempts,setAttempts]=useState(0), [errors,setErrors]=useState(0);
 const input=useRef(), startTime=useRef(), audio=useRef();
 const text = (difficulty==='easy' ? easyPassages : passages)[index % (difficulty==='easy'?easyPassages.length:passages.length)];
 const correct=[...typed].filter((c,i)=>c===text[i]).length;
 const wpm=elapsed>0 ? Math.round(correct/5/(elapsed/60)) : 0;
 const accuracy=attempts ? Math.round((attempts-errors)/attempts*100) : 100;
 const firstError=[...typed].findIndex((c,i)=>c!==text[i]);
 const progress=(firstError===-1?typed.length:firstError)/text.length;
 const botProgress=mode==='race'?[Math.min(elapsed*5*48/60/text.length,1),Math.min(elapsed*5*39/60/text.length,1)]:[0,0];
 const position=1+botProgress.filter(p=>status==='finished' ? p>=1 : p>progress).length;
 const best=history.length?Math.max(...history.map(h=>h.wpm)):0;
 const average=history.length?Math.round(history.reduce((s,h)=>s+h.wpm,0)/history.length):0;
 const today=history.filter(h=>new Date(h.date).toDateString()===new Date().toDateString()).length;
 useEffect(()=>{try{localStorage.setItem('shift-history',JSON.stringify(history));}catch{}},[history]);
 useEffect(()=>{try{localStorage.setItem('shift-color',JSON.stringify(color));}catch{}},[color]);
 useEffect(()=>{
  if(status!=='countdown')return;
  const id=setTimeout(()=>{if(count>1)setCount(count-1);else{setStatus('running');startTime.current=performance.now();setTimeout(()=>input.current?.focus(),50);}},1000);
  return()=>clearTimeout(id);
 },[status,count]);
 useEffect(()=>{
  if(status!=='running')return;
  const id=setInterval(()=>setElapsed((performance.now()-startTime.current)/1000),100);
  return()=>clearInterval(id);
 },[status]);
 useEffect(()=>{if(status==='running' && mode==='time' && elapsed>=30)finish();},[elapsed,status,mode]);
 useEffect(()=>{
  const key=e=>{if(e.key==='Escape'){setFocus(false);setModal(null);input.current?.blur();} if(e.key==='Tab' && e.shiftKey){e.preventDefault();reset();}};
  window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);
 });
 function reset(next=false) {setStatus('idle');setTyped('');setElapsed(0);setAttempts(0);setErrors(0);setCount(3);if(next)setIndex(i=>i+1);}
 function chooseMode(next){reset();setMode(next);setTab('race');}
 function beep(bad) {if(!sound)return;try {audio.current??=new (window.AudioContext||window.webkitAudioContext)();const a=audio.current,o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=bad?150:500;o.connect(g);g.connect(a.destination);g.gain.setValueAtTime(.025,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.055);o.start();o.stop(a.currentTime+.06);}catch{}}
 function finish(finalText=typed, finalAccuracy=accuracy) {
  if(status!=='running')return;
  const duration=(performance.now()-startTime.current)/1000;
  const score=Math.round([...finalText].filter((c,i)=>c===text[i]).length/5/(Math.max(duration,1)/60));
  setElapsed(duration);setStatus('finished');
  setHistory(h=>[{date:new Date().toISOString(),wpm:score,accuracy:finalAccuracy,mode},...h].slice(0,100));
 }
 const onType = useCallback((e) => {
  if(status!=='running')return;
  const value=e.target.value;
  if(value.length>text.length)return;
  let prefix=0;
  while(prefix<typed.length && prefix<value.length && typed[prefix]===value[prefix])prefix++;
  const added=value.slice(prefix);
  const wrong=[...added].filter((c,i)=>c!==text[prefix+i]).length;
  if(added.length){setAttempts(a=>a+added.length);setErrors(a=>a+wrong);beep(wrong>0);}
  setTyped(value);
  if(value===text)finish(value,attempts+added.length?Math.round((attempts+added.length-errors-wrong)/(attempts+added.length)*100):100);
 }, [status, typed, text, sound, attempts, errors, mode]);
 const nav=(target)=>{setTab(target);if(target==='garage')setModal('garage');};
 return <div className={`app ${focus?'focus-mode':''}`}>
  <header className="header"><a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('race');}} aria-label="Shift home"><span className="brand-mark"><i/><i/><i/></span>shift<span className="brand-dot">.</span></a><nav aria-label="Main navigation"><button className={tab==='race'?'active':''} onClick={()=>nav('race')}><Flag size={15}/>Race</button><button className={tab==='stats'?'active':''} onClick={()=>nav('stats')}><ChartNoAxesColumnIncreasing size={16}/>Stats</button><button className={tab==='friends'?'active':''} onClick={()=>{reset();nav('friends');}}><Flag size={16}/>Race friends</button><button onClick={()=>nav('garage')}><CarFront size={17}/>Garage</button></nav><div className="header-right"><span className="local-indicator"><i/>{tab==='friends'?'FRIENDS MULTIPLAYER':'PRACTICE SERVER'}</span><button className="avatar" aria-label="Open your profile" onClick={()=>setModal('profile')}>Y</button></div></header>
  <main>
   <section className="intro"><div><div className="eyebrow"><span/> THE NEXT GENERATION OF TYPING</div><h1>TYPE FAST.<br/><span>TAKE THE LEAD.</span></h1><p>Hit the keys. Own the track. Turn your speed into a victory.</p></div><div className="hero-right"><div className="hero-emblem"><Flag size={30}/><span>SHIFT<span>RACING CLUB</span></span><b>01</b></div><div className="hero-meta"><span><i/> 3D TYPING ARENA</span><button className="how-to" onClick={()=>setModal('help')}>How to play <ArrowUpRight size={14}/></button></div></div></section>
   {tab==='friends'?<Multiplayer color={color} onResult={result=>setHistory(h=>[result,...h].slice(0,100))}/>:tab==='stats'?<section className="progress-page"><div className="section-heading"><h2>Your progress</h2><button className="primary" onClick={()=>setTab('race')}>Back to racing <ArrowRight size={16}/></button></div><div className="stat-grid"><Stat value={best||'—'} label="Personal best · WPM"/><Stat value={average||'—'} label="Average speed · WPM"/><Stat value={history.length} label="Completed sessions"/></div><h3>Race history</h3>{history.length?<div className="history-list">{history.map((r,i)=><div className="history-row" key={r.date}><span>{new Date(r.date).toLocaleDateString()} <small>{new Date(r.date).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></span><span>{r.mode==='friends'?'Friends race':r.mode==='race'?'Quick race':r.mode==='time'?'Time trial':'Zen practice'}</span><strong>{r.wpm} <small>WPM</small></strong><span>{r.accuracy}% accuracy</span></div>)}</div>:<div className="empty"><Gauge size={36}/><h3>Your starting line is right here.</h3><p>Complete your first race to start building your personal record.</p><button className="primary" onClick={()=>setTab('race')}>Start a race <ArrowRight size={16}/></button></div>}</section>:
   <><div className="mode-bar"><div className="mode-tabs" role="tablist" aria-label="Race mode"><button role="tab" aria-selected={mode==='race'} className={mode==='race'?'selected':''} onClick={()=>chooseMode('race')}><Zap size={16}/>Quick race</button><button role="tab" aria-selected={mode==='time'} className={mode==='time'?'selected':''} onClick={()=>chooseMode('time')}><Timer size={16}/>Time trial</button><button role="tab" aria-selected={mode==='zen'} className={mode==='zen'?'selected':''} onClick={()=>chooseMode('zen')}><Leaf size={16}/>Zen mode</button></div><div className="race-settings"><button className="invite-entry" onClick={()=>{reset();setTab('friends');}}><Flag size={14}/> Race with friends <ArrowUpRight size={13}/></button><span>English</span><span className="divider"/><select aria-label="Typing difficulty" disabled={status==='running'||status==='countdown'} value={difficulty} onChange={e=>{reset();setDifficulty(e.target.value);}}><option value="normal">Normal difficulty</option><option value="easy">Easy difficulty</option></select><Settings2 size={15}/></div></div>
   <div className="workspace"><div className="race-column">
    <section className="track-card"><div className="track-heading"><span className="track-tag"><span className="tiny-dot"/>{mode==='race'?'NEON CIRCUIT':mode==='time'?'SPRINT CIRCUIT':'FREE DRIVE'}</span><span className="practice-label">{mode==='race'?'3 DRIVERS / AI LOBBY':'SOLO SESSION'} <span className="tiny-square"/></span></div><div className="track-copy"><h2>{status==='idle'?'WELCOME TO THE GRID.':status==='countdown'?'LIGHTS OUT IN…':status==='finished'?'FINISH LINE.':'FULL THROTTLE.'}</h2><p>{status==='idle'?'Three lanes. One goal. Leave your best time behind.':status==='countdown'?'Get ready to put your speed to the test.':status==='finished'?'Another lap in the books. Ready to go again?':mode==='zen'?'Your road. Your pace.':'Every correct keystroke moves you forward.'}</p></div><RaceScene progress={[progress,...botProgress]} running={status==='running'} color={color} solo={mode!=='race'}/><div className="track-coordinate">SECTOR 01 <span>///</span> NIGHT RUN</div><div className="track-bottom"><span><span className="car-dot" style={{background:color}}/> YOU <span className="you-tag">{status==='running'?`${position}${position===1?'ST':position===2?'ND':'RD'}`:'READY'}</span></span><span className="track-distance">{Math.round(progress*100)}% <span>/ FINISH LINE</span><Flag size={13}/></span></div>{status==='countdown'&&<div className="countdown" aria-live="assertive">{count}</div>}</section>
    <section className={`typing-card ${status==='running'?'is-running':''}`}>
     <div className="typing-heading"><div className="typing-title"><Keyboard size={16}/><span>{status==='finished'?'RACE REPORT':status==='running'?'RACE IN PROGRESS':'READY TO RACE'}</span></div><div className="typing-tools"><button aria-label={sound?'Mute typing sound':'Enable typing sound'} aria-pressed={sound} onClick={()=>setSound(!sound)}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><button aria-label="Restart race" onClick={()=>reset()}><RotateCcw size={15}/></button><button aria-label={focus?'Exit focus mode':'Enter focus mode'} onClick={()=>setFocus(!focus)}>{focus?<X size={17}/>:<Maximize2 size={15}/>}</button></div></div>
     {status==='finished'?<div className="results"><div className="finish-icon"><Trophy size={26}/></div><h2>{wpm>=best?'A new benchmark.':'Nicely driven.'}</h2><p>{mode==='race'?`You finished ${position===1?'1st':position===2?'2nd':'3rd'} against the AI racers.`:'One more session. A little more progress.'}</p><div className="result-stats"><Stat value={wpm} label="words per minute"/><Stat value={`${accuracy}%`} label="accuracy"/><Stat value={`${Math.round(elapsed)}s`} label="time on track"/></div><button className="primary" onClick={()=>{reset(true);}}>Race again <ArrowRight size={17}/></button></div>:<><TypingSurface ref={input} text={text} value={typed} onChange={onType} disabled={status!=='running'} label="Type the passage here"/><div className="typing-action">{status==='idle'?<><button className="primary" onClick={()=>{setCount(3);setStatus('countdown');}}>START RACE <ArrowRight size={17}/></button><span>YOUR KEYBOARD IS THE ACCELERATOR.</span></>:status==='countdown'?<span className="get-ready">Get ready — your race is about to begin</span>:<><span className="running-hint"><i/> {typed && typed!==text.slice(0,typed.length)?'Use backspace to correct the highlighted letters.':'Find your rhythm. Keep your eyes on the next word.'}</span><button className="text-button" onClick={()=>input.current?.focus()}>Focus input <ArrowUpRight size={14}/></button></>}</div></>}
     <div className="metrics"><div><strong>{wpm}<small>WPM</small></strong><span>Speed</span></div><div><strong>{accuracy}<small>%</small></strong><span>Accuracy</span></div><div><strong>{mode==='time'?Math.max(0,30-Math.floor(elapsed)):Math.floor(elapsed)}<small>s</small></strong><span>{mode==='time'?'Remaining':'Elapsed'}</span></div><div><strong>{mode==='race'?position:'—'}<small>{mode==='race'?'/ 3':''}</small></strong><span>{mode==='race'?'Position':'Solo run'}</span></div></div>
    </section><div className="keyboard-tip"><span><kbd>shift</kbd> + <kbd>tab</kbd> restart race <span className="tip-dot">·</span> <kbd>esc</kbd> exit focus</span><span>STAY SHARP. STAY AHEAD.</span></div>
   </div><aside>
    <section className="personal-card"><div className="aside-heading"><h3>PERSONAL RECORD</h3><Trophy size={17}/></div><div className="personal-best">{best||'—'}<span>WPM</span></div><div className="best-note">{best?'The only competition that counts.':'Your first finish sets the benchmark.'}</div><div className="mini-chart" aria-hidden="true">{[14,19,16,27,22,31,26,39,31,44,38,49,43,57,51,67,61,76,71,86,82,94].map((h,i)=><i key={i} style={{height:`${history.length?Math.max(12,Math.min(100,(history[Math.min(i,history.length-1)].wpm||20))):h}%`,opacity:history.length?1:.55}}/>)}</div><div className="chart-label"><span>{history.length?'RECENT SESSIONS':'YOUR POTENTIAL'}</span><span><ArrowUpRight size={12}/> KEEP GOING</span></div><button className="card-link" onClick={()=>setTab('stats')}>View your progress <ArrowUpRight size={15}/></button></section>
    <section className="daily-card"><div className="aside-heading"><h3>DAILY MISSION</h3><Flame size={18}/></div><p>Complete 5 races. Build your streak.</p><div className="daily-numbers"><span>Daily race goal</span><strong>{Math.min(today,5)} <span>/ 5</span></strong></div><div className="goal-bars">{Array.from({length:5},(_,i)=><i key={i} className={i<today?'done':''}/>)}</div><span className="daily-note">{today>=5?'Goal complete. That’s how progress happens.':`${5-Math.min(today,5)} ${5-today===1?'race':'races'} to build your momentum.`}</span></section>
    <section className="garage-card"><div className="garage-icon"><CarFront size={22}/></div><div><h3>CUSTOMIZE YOUR RIDE</h3><p>New color. Same competitive edge.</p></div><button onClick={()=>setModal('garage')} aria-label="Customize your car"><ArrowUpRight size={18}/></button><div className="swatches">{['#d5ef66','#f09969','#a7bddd','#eeeae0'].map(c=><button key={c} aria-label={`Choose ${c} car color`} aria-pressed={color===c} style={{background:c}} onClick={()=>setColor(c)}>{c===color&&<Check size={12}/>}</button>)}<span>YOUR COLOR. YOUR LANE.</span></div></section>
    <section className="lobby-card"><div className="lobby-title"><span>THE GRID</span><span>{mode==='race'?'3 / 3':'1 / 1'}</span></div>{[{name:'YOU',tag:'PLAYER',speed:wpm,color},...(mode==='race'?[{name:'GHOST',tag:'AI DRIVER',speed:48,color:'#bb8eff'},{name:'APEX',tag:'AI DRIVER',speed:39,color:'#65cfff'}]:[])].map((driver,i)=><div className="driver-row" key={driver.name}><span className="driver-number">0{i+1}</span><span className="driver-swatch" style={{background:driver.color}}/><div><strong>{driver.name}</strong><small>{driver.tag}</small></div><span className="driver-speed">{status==='running'||status==='finished'?driver.speed:'—'} <small>WPM</small></span></div>)}</section>
   </aside></div></>}
  </main><footer><span className="footer-brand">shift.</span><span>BUILT FOR SPEED. POWERED BY YOU.</span><div><button onClick={()=>setModal('feedback')}>About this build <ArrowUpRight size={12}/></button><span className="footer-status"><i/> All systems go</span><span>v.02</span></div></footer>
  {modal&&<div className="modal-backdrop" onClick={()=>{setModal(null);if(tab==='garage')setTab('race');}}><section className={`modal ${modal==='garage'?'showroom-modal':''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()}><button className="close-modal" autoFocus aria-label="Close dialog" onClick={()=>{setModal(null);if(tab==='garage')setTab('race');}}><X size={20}/></button>{modal==='garage'?<Garage color={color} onColorChange={setColor} onClose={()=>{setModal(null);setTab('race');}}/>:modal==='help'?<><div className="modal-eyebrow"><Keyboard size={18}/> FIND YOUR RHYTHM</div><h2 id="modal-title">Fast fingers. Open road.</h2><ol className="instructions"><li><strong>Pick your pace.</strong><p>Race friends creates a private live lobby for three human drivers. Quick race puts you against two AI drivers. Time trial is a 30-second sprint. Zen is untimed practice.</p></li><li><strong>Type what you see.</strong><p>Hit “Let’s race” and wait for the countdown. Match the passage exactly, including punctuation.</p></li><li><strong>Accuracy drives speed.</strong><p>Bright letters are correct. Red letters need a backspace. Complete the passage to cross the finish line.</p></li></ol><p className="modal-footnote">Your race history and car finish are saved in this browser.</p></>:modal==='profile'?<><div className="modal-eyebrow"><Gauge size={18}/> DRIVER PROFILE</div><h2 id="modal-title">Welcome to your lane.</h2><p>You’re racing as a local guest. No account needed — your progress stays in this browser.</p><div className="stat-grid"><Stat value={history.length} label="Races completed"/><Stat value={best||'—'} label="Best WPM"/></div></>:<><div className="modal-eyebrow"><Flag size={18}/> SHIFT / VERSION 02</div><h2 id="modal-title">A better kind of typing race.</h2><p>A playable local prototype with real 3D cars, AI opponents, time trials, and personal progress. Create a private room to race up to two friends live, using the same passage and synchronized start.</p><p>3D Ferrari model from the Three.js example collection, credited there to vicent091. Rendering powered by Three.js.</p><a className="card-link" href="https://threejs.org/examples/#webgl_loader_gltf_ferrari" target="_blank" rel="noreferrer">View model source <ArrowUpRight size={16}/></a></>}</section></div>}
 </div>;
}
function Stat({value,label}){return <div className="stat"><strong>{value}</strong><span>{label}</span></div>}
createRoot(document.getElementById('root')).render(<App/>);
