import React,{useEffect,useRef,useState,useCallback} from 'react';
import {Users,Link,Copy,Check,ArrowRight,LogOut,Flag,Trophy,Wifi,WifiOff,Crown,LoaderCircle} from 'lucide-react';
import RaceScene from './RaceScene';
import TypingSurface from './TypingSurface';
import './multiplayer.css';

const sessionKey='shift-room-session';
function stored(key,fallback,storage=localStorage){try{return JSON.parse(storage.getItem(key))??fallback;}catch{return fallback;}}
function roomFrom(value){try{value=new URL(value).searchParams.get('room')||'';}catch{}return value.trim().toUpperCase();}
function ordinal(n){return n===1?'1st':n===2?'2nd':'3rd';}

export default function Multiplayer({color,onResult}){
 const [name,setName]=useState(()=>stored('shift-driver-name',''));
 const [code,setCode]=useState(()=>new URLSearchParams(location.search).get('room')||'');
 const [room,setRoom]=useState(null),[connection,setConnection]=useState('connecting'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[typed,setTyped]=useState(''),[clock,setClock]=useState(Date.now()),[publicUrl,setPublicUrl]=useState(null),[offset,setOffset]=useState(0);
 const socket=useRef(),session=useRef(stored(sessionKey,null,sessionStorage)),roomRef=useRef(),sequence=useRef(0),raceRef=useRef(null),input=useRef(),recorded=useRef(new Set()),bestRtt=useRef(Infinity),resultCallback=useRef(onResult),mounted=useRef(true);
 resultCallback.current=onResult;roomRef.current=room;
 const me=room?.players.find(p=>p.id===room.you),isHost=room?.hostId===room?.you;
 const inputQueue=useRef([]),inputTimer=useRef();
 const serverNow=clock+offset;
 const countdown=room?.startsAt?Math.max(0,Math.ceil((room.startsAt-serverNow)/1000)):0;
 const active=(room?.status==='racing'||room?.status==='countdown')&&countdown===0;
 const canType=connection==='connected'&&active&&!me?.finishedAt&&!me?.dnf;
 const remaining=room?.status==='finished'?0:room?.endsAt?Math.min(120,Math.max(0,Math.ceil((room.endsAt-serverNow)/1000))):120;
 const order=room?[me,...room.players.filter(p=>p.id!==room.you)].filter(Boolean):[];
 const invite=room?`${publicUrl||location.origin}/?room=${room.code}`:'';
 const isLocalInvite=invite&&/^https?:\/\/(localhost|127\.0\.0\.1)(:|\/)/.test(invite);
 function saveSession(value){session.current=value;try{value?sessionStorage.setItem(sessionKey,JSON.stringify(value)):sessionStorage.removeItem(sessionKey);}catch{}}
 function send(data){if(socket.current?.readyState!==WebSocket.OPEN){setError('Connection lost. Reconnecting to your room…');return false;}socket.current.send(JSON.stringify(data));return true;}
 useEffect(()=>{
  mounted.current=true;let stopped=false,reconnect,pinger,attempt=0;const queryCode=new URLSearchParams(location.search).get('room');
  if(queryCode&&session.current&&session.current.code!==queryCode.toUpperCase())saveSession(null);
  fetch('/api/config').then(r=>r.json()).then(data=>{if(!stopped)setPublicUrl(data.publicUrl);}).catch(()=>{});
  function connect(){if(stopped)return;setConnection(attempt?'reconnecting':'connecting');const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);socket.current=ws;
   ws.onopen=()=>{attempt=0;setConnection('connected');bestRtt.current=Infinity;if(session.current)ws.send(JSON.stringify({type:'resume',...session.current}));ws.send(JSON.stringify({type:'ping',sentAt:Date.now()}));pinger=setInterval(()=>{if(ws.readyState===1)ws.send(JSON.stringify({type:'ping',sentAt:Date.now()}));},5000);};
   ws.onmessage=event=>{if(stopped)return;let data;try{data=JSON.parse(event.data);}catch{return;}
    if(data.type==='hello')setOffset(data.serverTime-Date.now());
    if(data.type==='pong'){const rtt=Date.now()-data.sentAt;if(rtt<=bestRtt.current){bestRtt.current=rtt;setOffset(data.serverTime-(data.sentAt+rtt/2));}}
    if(data.type==='joined'){saveSession({code:data.code,token:data.token});raceRef.current=null;clearTimeout(inputTimer.current);inputQueue.current=[];setCode(data.code);setError('');setBusy(false);history.replaceState(null,'',`${location.pathname}?room=${data.code}`);}
    if(data.type==='state'){
     const raceKey=`${data.code}:${data.raceId}:${data.status==='lobby'?'lobby':'race'}`;
     if(raceRef.current!==raceKey){raceRef.current=raceKey;sequence.current=Math.max(0,data.ackSeq??0);setTyped(data.yourText||'');}
     else if((data.ackSeq??-1)>=sequence.current){sequence.current=data.ackSeq;setTyped(data.yourText||'');}
     setRoom(data);setBusy(false);
    }
    if(data.type==='error'){setError(data.message);setBusy(false);if(['ROOM_NOT_FOUND','RESUME_FAILED','ROOM_EXPIRED'].includes(data.code)){saveSession(null);setRoom(null);}}
    if(data.type==='left'){saveSession(null);setRoom(null);setTyped('');setBusy(false);setCode('');raceRef.current=null;history.replaceState(null,'',location.pathname);}
    if(data.type==='replaced'){saveSession(null);setRoom(null);setConnection('offline');setError('This driver session is now open in another tab. Reload to join as a new driver.');stopped=true;clearInterval(pinger);}
   };
   ws.onclose=()=>{clearInterval(pinger);if(stopped)return;setBusy(false);setConnection('reconnecting');reconnect=setTimeout(connect,Math.min(1000*2**attempt++,5000));};ws.onerror=()=>{};
  }
  connect();const timer=setInterval(()=>setClock(Date.now()),100);
  return()=>{stopped=true;mounted.current=false;clearTimeout(reconnect);clearTimeout(inputTimer.current);clearInterval(pinger);clearInterval(timer);socket.current?.close();};
 },[]);
 useEffect(()=>{if(canType)input.current?.focus();},[canType]);
 useEffect(()=>{if(!me?.finishedAt||!room)return;const key=`${room.code}:${room.raceId}`;if(recorded.current.has(key))return;recorded.current.add(key);const prior=stored('shift-recorded-rooms',[]);if(prior.includes(key))return;try{localStorage.setItem('shift-recorded-rooms',JSON.stringify([...prior,key].slice(-100)));}catch{}resultCallback.current({date:new Date(me.finishedAt).toISOString(),wpm:me.wpm,accuracy:me.accuracy,mode:'friends'});},[me?.finishedAt,room?.raceId]);
 function enter(type){setError('');if(!name.trim()){setError('Choose a driver name first.');return;}if(type==='join'&&!/^[A-F0-9]{10}$/.test(roomFrom(code))){setError('Enter the 10-character room code, or paste the full invite link.');return;}try{localStorage.setItem('shift-driver-name',JSON.stringify(name.trim()));}catch{}setBusy(true);if(!send({type,name:name.trim(),color,code:roomFrom(code)}))setBusy(false);}
 async function copyInvite(){try{await navigator.clipboard.writeText(invite);setCopied(true);setTimeout(()=>mounted.current&&setCopied(false),2000);}catch{setError('Select and copy the invite link below.');}}
 function flushInput(){clearTimeout(inputTimer.current);inputTimer.current=null;if(inputQueue.current.length){const updates=inputQueue.current.splice(0,12);send({type:'inputs',updates});}}
 const type=useCallback((e)=>{if(!canType)return;const value=e.target.value;if(value.length>room.passage.length)return;setTyped(value);inputQueue.current.push({raceId:room.raceId,seq:++sequence.current,text:value});if(inputQueue.current.length>=12||value===room.passage)flushInput();else if(!inputTimer.current)inputTimer.current=setTimeout(flushInput,50);},[canType,room?.passage,room?.raceId]);
 function action(type,extra={}){setError('');setBusy(true);if(!send({type,...extra}))setBusy(false);}
 const statusText=connection==='connected'?'LIVE CONNECTION':connection==='connecting'?'CONNECTING':'RECONNECTING';
 return <section className="friends-page">
  <div className="friends-heading"><div><div className="modal-eyebrow"><Users size={16}/> PRIVATE MULTIPLAYER</div><h2>{room?'YOUR FRIENDS. YOUR GRID.':'THE BEST RIVALRY IS PERSONAL.'}</h2><p>{room?'Same passage. Same start. Settle it on the track.':'Create a room, share the invite, and race up to two friends live.'}</p></div><span className={`connection-pill ${connection==='connected'?'online':''}`}>{connection==='connected'?<Wifi size={13}/>:<WifiOff size={13}/>} {statusText}</span></div>
  {error&&<div role="alert" className="room-error">{error}<button onClick={()=>setError('')} aria-label="Dismiss message">×</button></div>}
  {connection!=='connected'&&room&&<div className="room-notice">Your connection dropped. Typing is paused while we reconnect; the shared race clock continues.</div>}
  {!room?<div className="room-entry"><section className="entry-form"><div className="entry-title"><span>01</span><h3>CHOOSE YOUR DRIVER NAME</h3></div><label htmlFor="driver-name">Driver name</label><input id="driver-name" maxLength={18} placeholder="e.g. NightRider" value={name} onChange={e=>setName(e.target.value)} autoComplete="nickname" onKeyDown={e=>{if(e.key==='Enter')enter(code?'join':'create');}}/><div className="entry-actions"><button className="primary" disabled={busy||connection!=='connected'} onClick={()=>enter('create')}>{busy?<LoaderCircle size={16} className="spin"/>:<Users size={17}/>} CREATE A ROOM <ArrowRight size={17}/></button><span>Private invite · 3 players · No account needed</span></div><div className="join-divider"><span/>OR JOIN YOUR FRIENDS<span/></div><label htmlFor="room-code">Room code or invite link</label><div className="join-input"><input id="room-code" placeholder="Paste an invite link or room code" value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>e.key==='Enter'&&enter('join')}/><button disabled={busy||connection!=='connected'} onClick={()=>enter('join')}>JOIN <ArrowRight size={15}/></button></div></section><section className="entry-guide"><div className="entry-racing-icon"><Flag size={45}/></div><h3>BRING YOUR CREW.<br/><span>LEAVE THEM BEHIND.</span></h3><ol><li><b>01</b><div><strong>Share your private invite.</strong><p>Anyone with the link can take an open spot.</p></div></li><li><b>02</b><div><strong>Everyone hits Ready.</strong><p>The host starts the synchronized countdown.</p></div></li><li><b>03</b><div><strong>Race for the finish.</strong><p>Live cars, live standings, one shared passage.</p></div></li></ol></section></div>:
  <><div className="room-toolbar"><div className="room-id"><span>ROOM</span><strong>{room.code}</strong><span className="room-phase">{room.status==='lobby'?'LOBBY':room.status==='countdown'?'STARTING':room.status==='racing'?'RACING':'FINISHED'}</span></div><div className="room-toolbar-actions"><button onClick={copyInvite}><Copy size={14}/>{copied?'COPIED':'COPY INVITE'}</button><button onClick={()=>action('leave')} disabled={busy}><LogOut size={14}/> LEAVE ROOM</button></div></div>
  <div className="invite-line"><Link size={13}/><input aria-label="Invite link" value={invite} readOnly onFocus={e=>e.target.select()}/></div>
  {isLocalInvite&&<p className="local-link-note">This is a local preview link. Open the shared public game URL before creating a room for friends on other computers.</p>}
  <div className="multiplayer-grid"><div>
   <section className="track-card friends-track"><div className="track-heading"><span className="track-tag"><span className="tiny-dot"/> FRIENDS CIRCUIT</span><span className="practice-label">{room.players.length} / 3 HUMAN DRIVERS</span></div><div className="track-copy"><h2>{room.status==='lobby'?'ASSEMBLE YOUR CREW.':room.status==='finished'?'THE RESULTS ARE IN.':me?.finishedAt?'FINISH LINE.':'RACE YOUR RIVALS.'}</h2><p>{room.status==='lobby'?'Share the invite. All drivers must be ready.':me?.finishedAt?'You finished. Watch the rest of the grid cross the line.':'Correct keystrokes move your car toward the finish.'}</p></div><RaceScene progress={order.map(p=>p.progress)} running={active} color={me?.color||color} colors={order.map(p=>p.color)} activeCount={order.length} solo={false}/><div className="track-bottom"><span><span className="car-dot" style={{background:me?.color}}/>{me?.name} <span className="you-tag">{room.status==='lobby'?'READY UP':ordinal(me?.rank||1).toUpperCase()}</span></span><span className="track-distance">{room.status==='lobby'?'WAITING FOR DRIVERS':room.status==='finished'?'RACE COMPLETE':`${remaining}s REMAINING`}<Flag size={13}/></span></div>{room.status==='countdown'&&countdown>0&&<div className="countdown" role="status">{countdown}</div>}</section>
   {room.status==='lobby'?<section className="ready-panel"><div><h3>{room.players.length<2?'WAITING FOR A CHALLENGER':room.players.every(p=>p.ready&&p.connected)?'THE GRID IS READY':'GET READY TO RACE'}</h3><p>{room.players.length<2?'Copy the invite and send it to a friend.':isHost?'Once everyone is ready, you can start the race.':'Hit Ready. Your host will start the countdown.'}</p></div><div className="ready-actions"><button className={`ready-button ${me?.ready?'is-ready':''}`} disabled={busy||connection!=='connected'} onClick={()=>action('ready',{value:!me.ready})}><Check size={17}/>{me?.ready?'READY — CLICK TO UNREADY':'I’M READY'}</button>{isHost&&<button className="primary" disabled={busy||connection!=='connected'||room.players.length<2||room.players.some(p=>!p.ready||!p.connected)} onClick={()=>action('start')}>START RACE <ArrowRight size={16}/></button>}</div></section>:
    <section className={`typing-card ${canType?'is-running':''}`}><div className="typing-heading"><div className="typing-title"><Flag size={15}/>{room.status==='finished'?'FINAL RESULTS':me?.finishedAt?'YOU FINISHED':'SHARED RACE PASSAGE'}</div><span className="race-time">{room.status==='finished'?'RACE COMPLETE':`${remaining}s / 120s`}</span></div>
    {room.status==='finished'||me?.finishedAt?<div className="results"><div className="finish-icon"><Trophy size={26}/></div><h2>{me?.finishedAt?`${ordinal(me.rank)} PLACE. WELL DRIVEN.`:'TIME’S UP. NEXT LAP?'}</h2><p>{room.status!=='finished'?'Your result is saved. Waiting for the other drivers…':'Final positions are calculated by the server.'}</p><div className="result-stats"><div className="stat"><strong>{me?.wpm||0}</strong><span>WPM</span></div><div className="stat"><strong>{me?.accuracy??100}%</strong><span>ACCURACY</span></div><div className="stat"><strong>{me?.finishedAt?`${((me.finishedAt-room.startsAt)/1000).toFixed(1)}s`:'DNF'}</strong><span>FINISH TIME</span></div></div>{room.status==='finished'&&(isHost?<button className="primary" onClick={()=>action('rematch')} disabled={busy}>RACE AGAIN <ArrowRight size={17}/></button>:<p>Waiting for the host to open the next race.</p>)}</div>:
     <><TypingSurface ref={input} text={room.passage} value={typed} onChange={type} disabled={!canType} label="Type the shared passage"/><div className="typing-action"><span>{countdown>0?'WAIT FOR THE COUNTDOWN.':typed!==room.passage.slice(0,typed.length)?'BACKSPACE TO CORRECT THE RED LETTERS.':'TYPE THE PASSAGE EXACTLY. EVERY KEYSTROKE COUNTS.'}</span></div><div className="metrics"><div><strong>{me?.wpm||0}<small>WPM</small></strong><span>Speed</span></div><div><strong>{me?.accuracy??100}<small>%</small></strong><span>Accuracy</span></div><div><strong>{Math.round((me?.progress||0)*100)}<small>%</small></strong><span>Progress</span></div><div><strong>{me?.rank||1}<small>/ {room.players.length}</small></strong><span>Position</span></div></div></>}
    </section>}
  </div><aside className="friends-sidebar"><section className="friends-roster"><div className="lobby-title"><span>{room.status==='finished'?'FINAL STANDINGS':'LIVE GRID'}</span><span>{room.players.length} / 3</span></div>{[...room.players].sort((a,b)=>room.status==='lobby'?0:a.rank-b.rank).map(p=><div className={`roster-player ${p.id===room.you?'is-you':''}`} key={p.id}><div className="roster-top"><span className="driver-swatch" style={{background:p.color}}/><strong>{p.name}{p.id===room.you&&<small> YOU</small>}</strong>{p.id===room.hostId&&<Crown size={13} aria-label="Host"/>}<span className={`player-status ${p.ready||p.finishedAt?'ready':''}`}>{!p.connected?'OFFLINE':p.dnf?'DNF':p.finishedAt?ordinal(p.rank):room.status==='lobby'?(p.ready?'READY':'NOT READY'):`${Math.round(p.progress*100)}%`}</span></div><div className="player-progress"><i style={{width:`${p.progress*100}%`,background:p.color}}/></div><div className="roster-stats"><span>{room.status==='lobby'?(p.id===room.hostId?'ROOM HOST':'CHALLENGER'):`${p.wpm} WPM`}</span><span>{room.status==='lobby'?(p.connected?'CONNECTED':'RECONNECTING'):`${p.accuracy}% ACCURACY`}</span></div></div>)}{Array.from({length:3-room.players.length},(_,i)=><div className="empty-slot" key={i}><Users size={20}/><span>OPEN DRIVER SLOT</span><button onClick={copyInvite}>Invite a friend <ArrowRight size={12}/></button></div>)}</section><section className="room-rules"><h3>FAIR START. REAL RIVALS.</h3><p>Everyone gets the same passage and countdown. Results use the server’s clock. The race ends after all drivers finish or 2 minutes.</p><p>Keep this tab open while racing. A disconnected driver can rejoin by refreshing.</p></section></aside></div></>}
 </section>;
}
